/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package hello

import org.scalatest.flatspec.AnyFlatSpec
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFlatSpec {
  // test("App has a greeting") {
  //   assert(App.greeting() != null)
  // }
  it should "say hello to Sue" in {
    assert(App.greeting() === "Hello, world!")
  }
}
