/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package hello

import zhttp.http._
import zhttp.service.Server
import zio._

object HelloWorld extends ZIOAppDefault {

  // Create HTTP route
  val app: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "text" => Response.text("Hello World!")
    case Method.GET -> !! / "json" =>
      Response.json("""{"greetings": "Hello World!"}""")
  }

  // Run it like any simple app
  override val run =
    Server.start(8090, app)
}

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    println(createPerson())
    println(stringDivideBy("400", "0"))
  }

  def createPerson(): String = {
    val p = Person(10, "Alex", "K");
    val p2 = p.copy(
      firstName = "Joe"
    );
    return "" + p2.id + " " + p2.name
  }

  def greeting(): String = "Hello, world!"

  def parseInt(str: String) =
    scala.util.Try(str.toInt).toOption

  def divide(a: Int, b: Int): Option[Int] =
    if (b == 0) None else Some(a / b)

  def stringDivideBy(aStr: String, bStr: String): Option[Int] =
    parseInt(aStr).flatMap { aNum =>
      parseInt(bStr).flatMap { bNum =>
        divide(aNum, bNum)
      }
    }
}


case class Person(id:Int, firstName: String, lastName: String) extends Employee, Human:
  val name: String = firstName + " " + lastName
  val age: Int = 100

